# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: WriteGoList
      run: go list -json -m all > go.list

    - name: Nancy
      uses: sonatype-nexus-community/nancy-github-action@main

    - name: Test
      run: go test -v -json ./... > TestResults-${{ matrix.go-version }}.json

    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-Results
        path: TestResults.json
